type: object
properties:
  fecha_inicio:
    type: string
    example: "2022-08-06"
  fecha_fin:
    type: string
    example: "2022-08-06"
  instrucciones:
    type: string
    example: Leer convocatoria
  activo:
    type: integer
    example: 1
    writeOnly: true
  archivo:
    type: string
    format: binary
    writeOnly: true
  examen_psicometrico_id:
    type: integer
    example: 1
    writeOnly: true
  examen_psicologico_id:
    type: integer
    example: 1
    writeOnly: true
required:
  - fecha_inicio
  - fecha_fin
  - instrucciones
