type: object
properties:
  id:
    type: integer
    example: 1
    readOnly: true
  activo:
    type: integer
    example: 1
  fecha_inicio:
    type: string
    example: "2022-08-06"
  fecha_fin:
    type: string
    example: "2022-08-06"
  instrucciones:
    type: string
    example: Leer convocatoria
  archivo:
    type: string
    format: binary
    writeOnly: true
  convocatoria_url:
    type: string
    example: htttp://localhost/imgs/configuraciones/convocatoria.png
    readOnly: true
  examen_psicometrico_id:
    type: integer
    example: 1
  examen_psicometrico:
    readOnly: true
    type: object
    properties:
      id:
        type: integer
        example: 1
        readOnly: true
      nombre:
        type: string
        example: Examen parcial uno de ecuaciones
      descripcion:
        type: string
        example: Resuelve los siguientes ejercicios
  examen_psicologico_id:
    type: integer
    example: 1
  examen_psicologico:
    readOnly: true
    type: object
    properties:
      id:
        type: integer
        example: 1
        readOnly: true
      nombre:
        type: string
        example: Examen parcial uno de ecuaciones
      descripcion:
        type: string
        example: Resuelve los siguientes ejercicios

required:
  - fecha_inicio
  - fecha_fin
  - instrucciones
