type: object
properties:
  id:
    type: integer
    example: 1
    readOnly: true
  nombre:
    type: string
    example: Inicio de sesión
  descripcion:
    type: string
    example: Foto de que aparece en la pantalla de inicio de sesión
  tipo:
    type: string
    example: image
  url:
    type: string
    example: htttp://localhost/imgs/configuraciones/login.png
    readOnly: true
  default:
    type: string
    example: htttp://localhost/imgs/configuraciones/login-default.png
    readOnly: true
  activo:
    type: integer
    example: 1
    writeOnly: true

required:
- nombre
- descripcion
- tipo
- activo
