type: object
properties:
  nombre:
    type: string
    example: Inicio de sesión
  descripcion:
    type: string
    example: Foto de que aparece en la pantalla de inicio de sesión
  tipo:
    type: string
    example: image
  archivo:
    type: string
    format: binary
    writeOnly: true
  activo:
    type: integer
    example: 1
    writeOnly: true

required:
- nombre
- descripcion
- tipo
- activo
