openapi: 3.0.0
info:
  title: DIXA API
  description: 'Proyecto DIXA API, gestión de documentación'
  version: 0.0.1
servers:
  - url: 'http://localhost:8000/api/v1'
    description: Servidor local
  - url: 'http://api.qa-dixa.puller.mx/api/v1'
    description: Servidor de qa
  - url: 'http://staging-dixa.puller.mx/api/v1'
    description: Servidor de staging
paths:
  /login:
    post:
      tags:
        - Auth
      security: []
      summary: Login de usuarios
      operationId: login
      description: login de usuario para la plataforma
      requestBody:
        description: Petición en formato json
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Estructura básica de la respuesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
  /logout:
    post:
      tags:
        - Auth
      summary: Logout de usuarios
      operationId: logout
      description: elimina el token del usuario que realiza la petición
      responses:
        '200':
          description: Estructura básica de la respuesta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ok
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
  /account:
    get:
      tags:
        - Auth
      summary: Cuenta
      operationId: account
      description: información del  usuario para la plataforma actualmente autenticado
      responses:
        '200':
          description: Estructura básica de la respuesta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
  /users:
    get:
      tags:
        - Usuarios
      summary: Get - Usuarios
      operationId: getUsuarios
      description: Obtiene el listado de todos los usuarios en una sola peticion
      parameters:
        - $ref: '#/components/parameters/nombre'
        - $ref: '#/components/parameters/role'
      responses:
        '200':
          description: Estructura básica de la respuesta
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Usuarios'
                  message:
                    type: string
                  success:
                    type: boolean
                    example: true
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
  /users/search:
    get:
      tags:
        - Usuarios
      summary: search - Usuarios
      operationId: searchUsuarios
      description: filtra usuarios paginado
      parameters:
        - $ref: '#/components/parameters/role'
        - $ref: '#/components/parameters/nombre'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/perPage'
        - $ref: '#/components/parameters/order'
        - $ref: '#/components/parameters/sortBy'
      responses:
        '200':
          description: Estructura básica de la respuesta
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Usuarios'
                  message:
                    type: string
                  success:
                    type: boolean
                    example: true
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/422'
components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
          example: email@puller.mx
        password:
          type: string
          format: password
          example: password
      required:
        - email
        - password
    Auth:
      type: object
      properties:
        access_token:
          type: string
          example: AS599879879sa87d98a7sd987ae7987a9
        user:
          $ref: '#/components/schemas/Usuarios'
        message:
          type: string
          example: Ok
        success:
          type: boolean
          example: true
    Account:
      type: object
      properties:
        data:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/Usuarios'
            roles:
              type: array
              items:
                type: string
              example:
                - Administrador
            permissions:
              type: object
              properties:
                nombre.permiso:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
            views:
              type: object
              properties:
                nombre.permiso.vista:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    path:
                      type: string
                      example: /dashboard
        message:
          type: string
          example: Ok
        success:
          type: boolean
          example: true
    Usuarios:
      type: object
      properties:
        id:
          type: integer
          example: 1
          readOnly: true
        email:
          type: string
          format: email
          example: correo@puller.mx
        email_verified_at:
          type: string
          example: '2020-01-01 12:00:00'
          readOnly: true
        nombre:
          type: string
          example: John
        paterno:
          type: string
          example: Doe
        materno:
          type: string
          example: Roblox
        celular:
          type: string
          example: 55 54 89 67 87
        password:
          type: string
          format: password
          example: C0ntr4s3n14
        imagen_file:
          type: string
          format: binary
          nullable: true
          writeOnly: true
        imagen:
          type: string
          format: url
          nullable: true
          readOnly: true
          example: 'https://s3.amazon/profile/46798a7fsd98f79asd8f7'
        departamento_id:
          type: integer
          nullable: true
          example: 1
        departamento:
          type: object
          properties:
            id:
              type: integer
              example: 1
            nombre:
              type: string
              example: Recursos Humanos
          nullable: true
          readOnly: true
      required:
        - email
        - nombre
        - paterno
        - materno
        - password
  parameters:
    page:
      in: query
      name: page
      description: pagina a consultar
      required: false
      schema:
        type: integer
        example: 1
    order:
      in: query
      name: order
      description: 'tipo de ordenamiento, descendente o ascendente'
      required: false
      schema:
        type: string
        enum:
          - asc
          - desc
    sortBy:
      in: query
      name: sortBy
      description: campo por el cual se desea ordenar
      required: false
      schema:
        type: string
        example: nombre
    perPage:
      in: query
      name: perPage
      description: cantidad de items que quieres que devuelva la respuesta
      required: false
      schema:
        type: integer
        example: 20
    role:
      in: query
      name: role
      description: (id del rol) Valor para filtrar el tipo de rol de los usuarios
      required: false
      schema:
        type: integer
        example: 1
    nombre:
      in: query
      name: nombre
      description: Valor para filtrar por nombre completo de usuario
      required: false
      schema:
        type: string
        example: John Doe
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    '400':
      description: Petición erronea
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: string
                example: Bad Request
              success:
                type: boolean
                example: false
    '401':
      description: No autenticado
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: string
                example: Unauthorized
              success:
                type: boolean
                example: false
    '403':
      description: No Autorizado
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: string
                example: Forbidden
              success:
                type: boolean
                example: false
    '404':
      description: Elemento no encontrado
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
                  example: Registro no encontrado
              success:
                type: boolean
                example: false
    '422':
      description: Error general de la petición
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
                  example: El campo key_name es obligatorio
              success:
                type: boolean
                example: false
    '500':
      description: Error del servidor
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: string
                example: Error del servidor
              success:
                type: boolean
                example: false
security:
  - bearerAuth: []
