post:
  tags: [configuracionAdmision]
  summary: "Create - ConfiguracionAdmision"
  operationId: createConfiguracionAdmision
  requestBody: { description: "Petición multipart/form-data", required: true, content: { multipart/form-data: { schema: { $ref: "../schemas/ConfiguracionAdmision/ConfiguracionAdmisionMultiPart.yaml" } } } }
  responses: { 200: { description: "Estructura básica de la respuesta", content: { application/json: { schema: { $ref: "../schemas/ConfiguracionAdmision/ConfiguracionAdmisionJson.yaml" } } } }, 422: { $ref: "../responses/error422.yaml" }, 404: { $ref: "../responses/error404.yaml" }, 401: { $ref: "../responses/error401.yaml" } }
get:
  tags: [configuracionAdmision]
  summary: "List -  ConfiguracionAdmision"
  operationId: listConfiguracionAdmision
  description: "Lista ConfiguracionAdmision"
  parameters:
    - $ref: "../parameters/query/page.yaml"
  responses:
    200:
      description: "Estructura básica de la respuesta"
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "../schemas/ConfiguracionAdmision/ConfiguracionAdmisionJson.yaml"
                maxItems: 10
              message:
                type: string
              success:
                type: boolean
                example: true
              links:
                $ref: "../meta-datos/links.yaml"
              meta:
                $ref: "../meta-datos/paginacion.yaml"
