get:
  tags: [configuracionAdmision]
  summary: "Get - ConfiguracionAdminision"
  operationId: getConfiguracionAdmision
  description: "Obtiene el  ConfiguracionAdminision"
  parameters:
    - $ref: "../parameters/path/configuracionAdmisionId.yaml"
  responses:
    {
      200:
        {
          description: "Estructura b치sica de la respuesta",
          content:
            {
              application/json:
                {
                  schema:
                    {
                      $ref: "../schemas/ConfiguracionAdmision/ConfiguracionAdmisionJson.yaml",
                    },
                },
            },
        },
      422: { $ref: "../responses/error422.yaml" },
      404: { $ref: "../responses/error404.yaml" },
      401: { $ref: "../responses/error401.yaml" },
    }
post:
  tags: [configuracionAdmision]
  summary: "Update - ConfiguracionAdminision"
  operationId: updateConfiguracionAdmision
  description: "Actualiza el  ConfiguracionAdminision"
  parameters:
    - $ref: "../parameters/path/configuracionAdmisionId.yaml"
  requestBody:
    {
      description: "Petici칩n multipart/form-data",
      content:
        {
          multipart/form-data:
            {
              schema:
                {
                  $ref: "../schemas/ConfiguracionAdmision/ConfiguracionAdmisionMultiPart.yaml",
                },
            },
        },
    }
  responses:
    {
      200:
        {
          description: "Estructura b치sica de la respuesta",
          content:
            {
              application/json:
                {
                  schema:
                    {
                      $ref: "../schemas/ConfiguracionAdmision/ConfiguracionAdmisionJson.yaml",
                    },
                },
            },
        },
      422: { $ref: "../responses/error422.yaml" },
      404: { $ref: "../responses/error404.yaml" },
      401: { $ref: "../responses/error401.yaml" },
    }
delete:
  tags: [configuracionAdmision]
  summary: "Delete - ConfiguracionAdminision"
  operationId: deleteConfiguracionAdmision
  description: "Borra el  ConfiguracionAdminision"
  parameters:
    - $ref: "../parameters/path/configuracionAdmisionId.yaml"
  responses:
    {
      200:
        {
          description: "Estructura b치sica de la respuesta",
          content:
            {
              application/json:
                {
                  schema:
                    {
                      $ref: "../schemas/ConfiguracionAdmision/ConfiguracionAdmisionJson.yaml",
                    },
                },
            },
        },
      422: { $ref: "../responses/error422.yaml" },
      404: { $ref: "../responses/error404.yaml" },
      401: { $ref: "../responses/error401.yaml" },
    }
