get:
  tags: [Configuraciones]
  summary: "Get - Configuraciones"
  operationId: getConfiguracion
  description: "Obtiene una configuración"
  parameters:
    - $ref: "../parameters/path/configuracionId.yaml"
  responses: { 200: { description: "Estructura básica de la respuesta", content: { application/json: { schema: { $ref: "../schemas/ConfiguracionesJson.yaml" } } } }, 422: { $ref: "../responses/error422.yaml" }, 404: { $ref: "../responses/error404.yaml" }, 401: { $ref: "../responses/error401.yaml" } }
post:
  tags: [Configuraciones]
  summary: "Update - Configuraciones"
  operationId: updateConfiguracion
  description: "Actualiza una configuración"
  parameters:
    - $ref: "../parameters/path/configuracionId.yaml"
  requestBody: { description: "Petición multipart/form-data", content: { multipart/form-data: { schema: { $ref: "../schemas/ConfiguracionesMultiPart.yaml" } } } }
  responses: { 200: { description: "Estructura básica de la respuesta", content: { application/json: { schema: { $ref: "../schemas/ConfiguracionesJson.yaml" } } } }, 422: { $ref: "../responses/error422.yaml" }, 404: { $ref: "../responses/error404.yaml" }, 401: { $ref: "../responses/error401.yaml" } }
delete:
  tags: [Configuraciones]
  summary: "Delete - Configuraciones"
  operationId: deleteConfiguracion
  description: "Borra una configuración"
  parameters:
    - $ref: "../parameters/path/configuracionId.yaml"
  responses: { 200: { description: "Estructura básica de la respuesta", content: { application/json: { schema: { $ref: "../schemas/ConfiguracionesJson.yaml" } } } }, 422: { $ref: "../responses/error422.yaml" }, 404: { $ref: "../responses/error404.yaml" }, 401: { $ref: "../responses/error401.yaml" } }
