post:
  tags: [Configuraciones]
  summary: "Create - Configuraciones"
  operationId: createConfiguracion
  description: "Crea una nueva configuraci칩n"
  requestBody: { description: "Petici칩n multipart/form-data", required: true, content: { multipart/form-data: { schema: { $ref: "../schemas/ConfiguracionesMultiPart.yaml" } } } }
  responses: { 200: { description: "Estructura b치sica de la respuesta", content: { application/json: { schema: { $ref: "../schemas/ConfiguracionesJson.yaml" } } } }, 422: { $ref: "../responses/error422.yaml" }, 404: { $ref: "../responses/error404.yaml" }, 401: { $ref: "../responses/error401.yaml" } }
get:
  tags: [Configuraciones]
  summary: "List - Configuraciones"
  operationId: listConfiguraciones
  description: "Lista Configuraciones"
  parameters:
    - $ref: "../parameters/query/page.yaml"
  responses:
    200:
      description: "Estructura b치sica de la respuesta"
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: "../schemas/ConfiguracionesJson.yaml"
                maxItems: 25
              message:
                type: string
              success:
                type: boolean
                example: true
              links:
                $ref: "../meta-datos/links.yaml"
              meta:
                $ref: "../meta-datos/paginacion.yaml"
