openapi: 3.0.0
info:
  title: DIXA API
  description: Proyecto DIXA API, gestión de documentación
  version: 0.0.1
servers:
  - url: http://localhost:8000/api/v1
    description: Servidor local
  - url: http://api.qa-dixa.puller.mx/api/v1
    description: Servidor de qa
  - url: http://staging-dixa.puller.mx/api/v1
    description: Servidor de staging

paths:
  /login:
    $ref: './paths/Login.yaml'
  /logout:
    $ref: './paths/Logout.yaml'
  /account:
    $ref: './paths/Account.yaml'
  /users:
    $ref: './paths/Users.yaml'
  /users:search:
    $ref: './paths/Users.yaml'

components:
  schemas:
    $ref: './schemas/_index.yaml'

  parameters:
    $ref: './parameters/_index.yaml'

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

  responses:
    $ref: './responses/_index.yaml'

security:
  - bearerAuth: []
