openapi: 3.0.0
info:
  title: DIXA API
  description: Project DIXA API, documentation management
  version: 0.0.1
servers:
  - url: http://localhost:8000/api/v1
    description: Servidor local
  - url: http://api.qa-dixa.puller.mx/api/v1
    description: Servidor de qa
  - url: http://staging-dixa.puller.mx/api/v1
    description: Servidor de staging

paths:
  /login:
    $ref: './paths/Login.yaml'
  /logout:
    $ref: './paths/Logout.yaml'
  /verify-auth:
    $ref: './paths/VerifyAuth.yaml'
  /account:
    $ref: './paths/Account.yaml'
  /admin/users/{user_id}/reset-password:
    $ref: './paths/AdminUsersByIdResetPassword.yaml'
  /users:
    $ref: './paths/Users.yaml'
  /users/{user_id}:
    $ref: './paths/UsersById.yaml'
  /users/{user_id}/change-password:
    $ref: './paths/UsersByIdChangePassword.yaml'
  /users/image:
    $ref: './paths/UsersImage.yaml'
  /users/search:
    $ref: './paths/UsersSearch.yaml'
  /roles:
    $ref: './paths/Roles.yaml'
  /roles/{role_id}:
    $ref: './paths/RolesById.yaml'
  /departments:
    $ref: './paths/Departments.yaml'
  /departments/{department_id}:
    $ref: './paths/DepartmentsById.yaml'
  /documents:
    $ref: './paths/Documents.yaml'
  /documents/{document_id}:
    $ref: './paths/DocumentsById.yaml'
  /folders:
    $ref: './paths/Folders.yaml'
  /share-permissions:
    $ref: './paths/SharePermissions.yaml'
  /documents/{document_id}/:rename:
    $ref: './paths/DocumentRenameById.yaml'
  /share-documents/{document_id}/users:
    $ref: './paths/ShareDocumentsUsers.yaml'
  /analyst-permissions:
    $ref: './paths/AnalystPermissions.yaml'
  /users/{user_id}/permissions:
    $ref: './paths/UsersPermissions.yaml'
  /users/*/permissions:
    $ref: './paths/UsersManyPermissions.yaml'
  /documents/{document_id}/tags:
    $ref: './paths/DocumentsTags.yaml'
  /documents/{document_id}/tags/{tag_name}:
    $ref: './paths/DocumentsTagsName.yaml'
  /share-documents/by-me:
    $ref: './paths/ShareDocumentsByMe.yaml'

components:
  schemas:
    $ref: './schemas/_index.yaml'

  parameters:
    $ref: './parameters/_index.yaml'

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

  responses:
    $ref: './responses/_index.yaml'

security:
  - bearerAuth: []
