openapi: 3.0.0
info:
  title: Bachiller API
  description: Bachiller API
  version: 0.0.1
servers:
  - url: http://localhost:8000/api/v1
    description: Sevidor local
  - url: http://api.qa-bachiller.puller.mx/api/v1
    description: Servidor de qa
  - url: http://staging-bachiller.puller.mx
    description: Servidor de staging

paths:
  /estados:
    $ref: "./paths/Estados.yaml"
  /estados/{estado_id}:
    $ref: "./paths/Estados-by-id.yaml"
  /estados/{estado_id}/municipios:
    $ref: "./paths/Municipios.yaml"
  /estados/{estado_id}/municipios/{municipio_id}:
    $ref: "./paths/Municipios-by-id.yaml"
  /tipos-material:
    $ref: "./paths/TiposMaterial.yaml"
  /tipos-material/{material_id}:
    $ref: "./paths/TiposMaterial-by-id.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades:
    $ref: "./paths/Unidades.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}:
    $ref: "./paths/Unidades-by-id.yaml"
  /preguntas-tipo:
    $ref: "./paths/PreguntasTipo.yaml"
  /preguntas-tipo/{pregunta_tipo_id}:
    $ref: "./paths/PreguntasTipo-by-id.yaml"
  /examenes-tipo:
    $ref: "./paths/ExamenesTipo.yaml"
  /examenes-tipo/{examen_tipo_id}:
    $ref: "./paths/ExamenesTipo-by-id.yaml"
  /configuracion-admision:
    $ref: "./paths/ConfiguracionAdmision.yaml"
  /configuracion-admision/{configuracion_admision_id}:
    $ref: "./paths/ConfiguracionAdmision-by-id.yaml"
  /aspirantes:
    $ref: "./paths/Aspirantes.yaml"
  /aspirantes/{usuario_id}/status:
    $ref: "./paths/AspirantesStatus-by-id.yaml"
  /aspirantes/{usuario_id}/correoTerminoExamen:
    $ref: "./paths/Aspirantes-correoTerminoExamen.yaml"
  /aspirantes/*/{curp}:
    $ref: "./paths/Aspirantes-curp.yaml"
  /usuarios:
    $ref: "./paths/Usuarios.yaml"
  /usuarios:search:
    $ref: "./paths/UsuariosSearch.yaml"
  /usuarios/*/importUsers:
    $ref: "./paths/UsuariosImport.yaml"
  /usuarios/*/exportUsers:
    $ref: "./paths/UsuariosExportados.yaml"
  /usuarios/{usuario_id}:
    $ref: "./paths/Usuarios-by-id.yaml"
  /usuarios/*/getFormatImportUsers:
    $ref: "./paths/UsuariosGetFormatImportUsers.yaml"
  /usuarios/{usuario_id}/datos-generales:
    $ref: "./paths/DatosGenerales.yaml"
  /usuarios/{usuario_id}/datos-generales/{datos_generales_id}:
    $ref: "./paths/DatosGenerales-by-id.yaml"
  /usuarios/{usuario_id}/datos-familiares:
    $ref: "./paths/DatosFamiliares.yaml"
  /usuarios/{usuario_id}/datos-familiares/{datos_familiares_id}:
    $ref: "./paths/DatosFamiliares-by-id.yaml"
  /usuarios/{usuario_id}/datos-academicos:
    $ref: "./paths/DatosAcademicos.yaml"
  /usuarios/{usuario_id}/datos-academicos/{datos_academicos_id}:
    $ref: "./paths/DatosAcademicos-by-id.yaml"
  /grupos:
    $ref: "./paths/Grupos.yaml"
  /grupos/{grupo_id}:
    $ref: "./paths/Grupos-by-id.yaml"
  /grupos/{grupo_id}/alumnos/*:bind:
    $ref: "./paths/Grupo-bind-alumnos.yaml"
  /grupos/{grupo_id}/alumnos/{usuario_id}:bind:
    $ref: "./paths/Grupo-bind-alumno.yaml"
  /grupos:search:
    $ref: "./paths/GruposSearch.yaml"
  /grupos/*/alumnos/{usuario_id}/calendario:
    $ref: "./paths/AlumnosGrupoCalendario.yaml"
  /configuraciones:
    $ref: "./paths/Configuraciones.yaml"
  /configuraciones/{configuracion_id}:
    $ref: "./paths/Configuraciones-by-id.yaml"
  /conferencias:
    $ref: "./paths/Conferencias.yaml"
  /conferencias/{conferencia_id}:
    $ref: "./paths/Conferencias-by-id.yaml"
  /conferencias:search:
    $ref: "./paths/ConferenciasSearch.yaml"
  /usuarios/{usuario_id}/actividades:
    $ref: "./paths/Actividades.yaml"
  /usuarios/{usuario_id}/actividades/{actividades_id}:
    $ref: "./paths/Actividades-by-id.yaml"
  /tutorias:
    $ref: "./paths/Tutorias.yaml"
  /tutorias/{tutoria_id}:
    $ref: "./paths/Tutorias-by-id.yaml"
  /tutorias/{tutoria_id}/imagen/{uuid}:
    $ref: "./paths/TutoriasImagen-by-id.yaml"
  /tutorias:search:
    $ref: "./paths/TutoriasSearch.yaml"
  /avisos:
    $ref: "./paths/Avisos.yaml"
  /avisos/{aviso_id}:
    $ref: "./paths/Avisos-by-id.yaml"
  /avisos:search:
    $ref: "./paths/AvisosSearch.yaml"
  /eventos:
    $ref: "./paths/Eventos.yaml"
  /eventos/{evento_id}:
    $ref: "./paths/Eventos-by-id.yaml"
  /eventos:search:
    $ref: "./paths/EventosSearch.yaml"
  /especialidades:
    $ref: "./paths/Especialidades.yaml"
  /especialidades/{especialidad_id}:
    $ref: "./paths/Especialidades-by-id.yaml"
  /especialidades:batchGet/{especialidad_id}:
    $ref: "./paths/EspecialidadesBatchGet.yaml"
  /periodos:
    $ref: "./paths/Periodos.yaml"
  /periodos/{periodo_id}:
    $ref: "./paths/Periodos-by-id.yaml"
  /componentes:
    $ref: "./paths/Componentes.yaml"
  /componentes/{componente_id}:
    $ref: "./paths/Componentes-by-id.yaml"
  /especialidades/{especialidad_id}/materias:
    $ref: "./paths/Materias.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}:
    $ref: "./paths/Materias-by-id.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}/temas:
    $ref: "./paths/Temas.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}/temas/{tema_id}:
    $ref: "./paths/Temas-by-id.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}/temas/{tema_id}/materiales-didacticos:
    $ref: "./paths/MaterialesDidacticos.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}/temas/{tema_id}/materiales-didacticos/{repositorio_id}:
    $ref: "./paths/MaterialesDidacticos-by-id.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}/temas/{tema_id}/materiales-didacticos/{repositorio_id}:copy:
    $ref: "./paths/MaterialesDidacticos-copy-by-id.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}/temas/{tema_id}/materiales-didacticos/{repositorio_id}:check:
    $ref: "./paths/MaterialesDidacticos-check-by-id.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}/tareas:
    $ref: "./paths/Tareas.yaml"
  /especialidades/{especialidad_id}/materias/{materia_id}/unidades/{unidad_id}/tareas/{tarea_id}:
    $ref: "./paths/Tareas-by-id.yaml"
  /periodos/{periodo_id}/contenidos-extra:
    $ref: "./paths/ContenidosExtra.yaml"
  /periodos/{periodo_id}/contenidos-extra/{contenido_extra_id}:
    $ref: "./paths/ContenidosExtra-by-id.yaml"
  /examenes:search:
    $ref: "./paths/ExamenesTodos.yaml"
  /examenes/examen/{examen_id}:copy:
    $ref: "./paths/ExamenesCopy.yaml"
  /examenes/{examen_id}/temas/{tema_id}:bind:
    $ref: "./paths/Examenes-bind-tema.yaml"
  /examenes/{examen_id}/temas/{tema_id}:unbind:
    $ref: "./paths/Examenes-unbind-tema.yaml"
  /examenes/{examen_id}/especialidad-periodo-grupo/{especialidad_periodo_grupo_id}:bind:
    $ref: "./paths/Examenes-bind-grupos.yaml"
  /examenes/{examen_id}/especialidad-periodo-grupo/{especialidad_periodo_grupo_id}:unbind:
    $ref: "./paths/Examenes-unbind-grupos.yaml"
  /examenes/{examen_id}/verificar-estado-respondido:
    $ref: "./paths/Examen-verificar-estado.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}:rate:
    $ref: "./paths/ExamenesCalificar.yaml"
  /usuarios/{usuario_id}/examenes:
    $ref: "./paths/Examenes.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}:
    $ref: "./paths/Examenes-by-id.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/examenes-preguntas:
    $ref: "./paths/ExamenesPreguntas.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/examenes-preguntas/{examenes_preguntas_id}:
    $ref: "./paths/ExamenesPreguntas-by-id.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/examenes-respuestas:
    $ref: "./paths/ExamenesRespuestasList.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/examenes-preguntas/{examenes_preguntas_id}/examenes-respuestas:
    $ref: "./paths/ExamenesRespuestas.yaml"
  /aspirantes/{usuario_id}/examenes/{examen_id}/examenes-preguntas/{examenes_preguntas_id}/examenes-respuestas:
    $ref: "./paths/ExamenesRespuestasAspirantes.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/examenes-preguntas/{examenes_preguntas_id}/examenes-respuestas/{examenes_respuestas_id}:
    $ref: "./paths/ExamenesRespuestas-by-id.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/examenes-calificaciones:
    $ref: "./paths/ExamenesCalificaciones.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/examenes-calificaciones/{examenes_calificaciones_id}:
    $ref: "./paths/ExamenesCalificaciones-by-id.yaml"
  /encuestas:
    $ref: "./paths/Encuestas.yaml"
  /encuestas:search:
    $ref: "./paths/EncuestasSearch.yaml"
  /encuestas/{encuesta_id}:
    $ref: "./paths/Encuestas-by-id.yaml"
  /encuestas/{encuesta_id}:copy:
    $ref: "./paths/EncuestasCopy.yaml"
  /encuestas/{encuesta_id}/resultados:
    $ref: "./paths/EncuestasResultados.yaml"
  /encuestas/{encuesta_id}/exportar:
    $ref: "./paths/EncuestaExportar.yaml"
  /encuestas/{encuesta_id}/encuestas-preguntas:
    $ref: "./paths/EncuestasPreguntas.yaml"
  /encuestas/{encuesta_id}/encuestas-preguntas/{encuestas_preguntas_id}:
    $ref: "./paths/EncuestasPreguntas-by-id.yaml"
  /encuestas/{encuesta_id}/encuestas-respuestas:
    $ref: "./paths/EncuestasRespuestas.yaml"
  /encuestas/{encuesta_id}/encuestas-respuestas/{encuestas_respuestas_id}:
    $ref: "./paths/EncuestasRespuestas-by-id.yaml"
  /examenes-banco-preguntas:
    $ref: "./paths/ExamenesBancoPreguntas.yaml"
  /examenes-banco-preguntas/{banco_pregunta_id}:
    $ref: "./paths/ExamenesBancoPreguntas-by-id.yaml"
  /examenes-banco-preguntas:search:
    $ref: "./paths/ExamenesBancoPreguntasSearch.yaml"
  /confirmar-email:
    $ref: "./paths/ConfirmarEmail.yaml"
  /veficar-email:
    $ref: "./paths/VerificarEmail.yaml"
  /permisos/*/usuarios:
    $ref: "./paths/Permisos-Usuario.yaml"
  /permisos/*/usuarios/{usuario_id}:
    $ref: "./paths/Permisos-Usuario-by-id.yaml"
  /materias:search:
    $ref: "./paths/MateriasSearch.yaml"
  /periodos:search:
    $ref: "./paths/PeriodosSearch.yaml"
  /temas:search:
    $ref: "./paths/TemasSearch.yaml"
  /unidades:search:
    $ref: "./paths/UnidadesSearch.yaml"
  /auth/roles:
    $ref: "./paths/Rol.yaml"
  /periodos:bind:
    $ref: "./paths/Periodos-bind.yaml"
  /periodos:unbind:
    $ref: "./paths/Periodos-unbind.yaml"
  /tareas:search:
    $ref: "./paths/TareasSearch.yaml"
  /especialidades/{especialidad_id}/periodos/{periodo_id}/materias/{materia_id}/unidades/{unidad_id}/tareas/{tarea_id}:copy:
    $ref: "./paths/TareasCopy.yaml"
  /tareas/{tarea_id}/grupos/{grupo_id}:bind:
    $ref: "./paths/Tareas-bind-grupo.yaml"
  /tareas/{tarea_id}/grupos/{grupo_id}:unbind:
    $ref: "./paths/Tareas-unbind-grupo.yaml"
  /tareas/{tarea_id}/temas/{tema_id}:bind:
    $ref: "./paths/Tareas-bind-tema.yaml"
  /tareas/{tarea_id}/temas/{tema_id}:unbind:
    $ref: "./paths/Tareas-unbind-tema.yaml"
  /bajas-tipo:
    $ref: "./paths/BajasTipo.yaml"
  /bajas-tipo/{baja_tipo_id}:
    $ref: "./paths/BajasTipo-by-id.yaml"
  /docentes/{usuario_id}/materias/{materia_id}:bind:
    $ref: "./paths/DocentesMateria-bind.yaml"
  /docentes/{usuario_id}/materias/{materia_id}:unbind:
    $ref: "./paths/DocentesMateria-unbind.yaml"
  /docentes/{usuario_id}/materias/{materia_id}/grupos:
    $ref: "./paths/DocentesMateria-Grupos.yaml"
  /docentes/*/calificar-tarea/{tarea_id}:
    $ref: "./paths/DocentesCalificarTarea.yaml"
  /docentes/*/calificar-examenes/{examen_id}:
    $ref: "./paths/DocentesCalificarExamen.yaml"
  /docentes/*/calificar-tarea/{tarea_id}/alumnos/{usuario_id}:
    $ref: "./paths/DocentesCalificarTarea-updateOrCreate.yaml"
  /docentes/{usuario_id}/materias/{materia_id}:
    $ref: "./paths/DocentesMateria.yaml"
  /docentes/{usuario_id}/calendario:
    $ref: "./paths/DocenteTareasExamenesCalendario.yaml"
  /docentes/*/alumnos-grupo/{especialidad_periodo_grupo_id}:
    $ref: "./paths/DocenteAlumnoGrupo.yaml"
  /docentes/*/tabla-calificacion/{docente_materia_id}:
    $ref: "./paths/DocenteTablaCalificacion.yaml"
  /docentes/*/tabla-calificacion/{docente_materia_id}/alumno/{usuario_id}:
    $ref: "./paths/DocenteTablaCalificacionAlumno.yaml"
  /docentes/{usuario_id}/pase-lista:
    $ref: "./paths/DocenteAsistenciaGrupo.yaml"
  /docentes/{docente_id}/pase-lista/*/alumnos/{alumno_id}:
    $ref: "./paths/DocenteAsistenciaAlumno.yaml"
  /docentes/{usuario_id}/pase-lista:search:
    $ref: "./paths/DocentePaseListaSearch.yaml"
  /docentes/{usuario_id}/materias:
    $ref: "./paths/DocenteMateriasGrupo.yaml"
  /docentes/*/exportsExamenesGrupo/{docente_materia_id}:
    $ref: "./paths/DocenteExportsExamenesGrupo.yaml"
  /docentes/*/tabla-rubrica/{docente_materia_id}:
    $ref: "./paths/DocenteTablaRubrica.yaml"
  /docentes/*/alumnos/*/mis-actividades/{id}:
    $ref: "./paths/DocenteCalificarMisActividades.yaml"
  /materias:batchGet/{materia_id}:
    $ref: "./paths/MateriasBatchGet.yaml"
  /usuarios/{usuario_id}/:baja:
    $ref: "./paths/UsuarioBaja.yaml"
  /usuarios/{usuario_id}/:reingreso:
    $ref: "./paths/UsuarioReingreso.yaml"
  /especialidad-periodo-grupo/{especialidad_periodo_grupo_id}:
    $ref: "./paths/EspecialidadPeriodoGrupo-by-id.yaml"
  /especialidad-periodo-grupo/{especialidad_periodo_grupo_id}/alumnos/*:
    $ref: "./paths/EspecialidadPeriodoGrupoAlumnos.yaml"
  /especialidad-periodo-grupo/{especialidad_periodo_grupo_id}/materias:
    $ref: "./paths/EspecialidadPeriodoMaterias.yaml"
  /especialidad-periodo-grupo:
    $ref: "./paths/EspecialidadPeriodoGrupo.yaml"
  /especialidad-periodo-grupo:search:
    $ref: "./paths/EspecialidadPeriodoGrupoSearch.yaml"
  /generaciones:
    $ref: "./paths/Generaciones.yaml"
  /materiales-didacticos:search:
    $ref: "./paths/MaterialesDidacticosSearch.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/timestamp:start:
    $ref: "./paths/TimestampStart.yaml"
  /usuarios/{usuario_id}/examenes/{examen_id}/timestamp:end:
    $ref: "./paths/TimestampEnd.yaml"
  /alumnos/{usuario_id}/tareas:search:
    $ref: "./paths/AlumnoTarea.yaml"
  /alumnos/{usuario_id}/tareas/*/tareas-enviadas:search:
    $ref: "./paths/AlumnoTareaEnviada.yaml"
  /alumnos/{usuario_id}/tareas/{tarea_id}:
    $ref: "./paths/AlumnoTarea-by-id.yaml"
  /alumnos/{usuario_id}/tareas/{tarea_id}/tareas-enviadas:
    $ref: "./paths/AlumnoTareaEnviadaMultiPart.yaml"
  /alumnos/{usuario_id}/mis-actividades:
    $ref: "./paths/AlumnoMisActividades-by-id.yaml"
  /alumnos/{usuario_id}/examenes:search:
    $ref: "./paths/AlumnoExamen.yaml"
  /alumnos/{usuario_id}/examenes/{examen_id}:
    $ref: "./paths/AlumnoExamen-by-id.yaml"
  /alumnos/{usuario_id}/tabla-calificacion:
    $ref: "./paths/AlumnoTablaCalificacion.yaml"
  /zoom/crearZoomMeeting:
    $ref: "./paths/ZoomCrearMeeting.yaml"
  /zoom/generarSignature:
    $ref: "./paths/ZoomGenerarSignature.yaml"
  /rubrica:
    $ref: "./paths/Rubrica.yaml"
  /rubrica/{rubrica_id}:
    $ref: "./paths/Rubrica-by-id.yaml"
  /rubrica-docente-materia/{docente_materia_id}:
    $ref: "./paths/Rubrica-by-docente-materia-id.yaml"
  /califacion-parcial/especialidad-periodo-grupo/{especialidad_periodo_grupo_id}/materias/{materia_id}/alumnos/{usuario_id}:
    $ref: "./paths/Calificacion-parcial.yaml"
  /califacion-parcial/especialidad-periodo-grupo/{especialidad_periodo_grupo_id}/materias/{materia_id}/alumnos:
    $ref: "./paths/Calificacion-parcial-alumnos.yaml"
  /califacion-parcial/*/alumnos/{usuario_id}/kardex:
    $ref: "./paths/Calificacion-parcial-alumnoKardex.yaml"
  /califacion-parcial/*/especialidad-periodo-grupo/{especialidad_periodo_grupo_id}/kardex:
    $ref: "./paths/Calificacion-parcial-gruposKardex.yaml"
  /califacion-parcial/*/alumno/{usuario_id}/rendimiento:
    $ref: "./paths/Calificacion-parcial-rendimiento.yaml"
  /califacion-parcial/*/alumnos/{usuario_id}/boleta:
    $ref: "./paths/Calificacion-parcial-alumnoBoleta.yaml"
  /califacion-parcial/*/especialidad-periodo-grupo/{especialidad_periodo_grupo_id}/boleta:
    $ref: "./paths/Calificacion-parcial-gruposBoleta.yaml"
  /califacion-parcial/*/especialidad-periodo-grupo/{especialidad_periodo_grupo_id}/materias/{materia_id}/acta-seguimiento:
    $ref: "./paths/Calificacion-parcial-acta.yaml"
  /infracciones:
    $ref: "./paths/Infracciones.yaml"
  /infracciones/{infraccion_id}:
    $ref: "./paths/Infracciones-by-id.yaml"
  /infracciones:search:
    $ref: "./paths/InfraccionesSearch.yaml"
  /docentes/{usuario_id}/alumnos:
    $ref: "./paths/ListaDeAlumnos.yaml"
  /especialidades-periodos:
    $ref: "./paths/EspecialidadPeriodos.yaml"
  /especialidades-periodos/{especialidad_periodo_id}:
    $ref: "./paths/EspecialidadPeriodos-by-id.yaml"
  /especialidades-periodos/{especialidad_periodo_id}/grupos-materias:
    $ref: "./paths/gruposMaterias.yaml"
  /especialidades-periodos-grupos/{especialidad_periodo_grupo_id}/docentes/{docente_id}/materias:
    $ref: "./paths/MateriasDocentePorEspecialidadPeriodoGrupo.yaml"
  /docentes/{usuario_id}/especialidades-periodos-grupos:
    $ref: "./paths/DocenteEspecialidadesPeriodosGrupos.yaml"
  /usuarios/cambio-clave:
    $ref: "./paths/cambioClave.yaml"

components:
  schemas:
    $ref: "./schemas/_index.yaml"

  parameters:
    $ref: "./parameters/_index.yaml"

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

  responses:
    $ref: "./responses/_index.yaml"

security:
  - bearerAuth: []
