#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# php artisan migrate:fresh
# php artisan db:seed --class=Database\\Seeders\\Testing\\PrePushSeeder
# php artisan passport:install --force
php artisan test --stop-on-failure
